"""Publish canonical test design drafts to Jira as standard Tasks."""

from __future__ import annotations

import uuid

from sqlalchemy.orm import Session

from app.connectors.jira_client import JiraClient, JiraClientError, plain_lines_to_adf, project_key_from_issue_key
from app.core.config import Settings
from app.core.constants import ActorType, AuditEventType
from app.db.models.jira_generated_test_case import JiraGeneratedTestCase
from app.publishers.base import TestDesignPublisher
from app.schemas.test_design_publish import PublishResult, TestCaseDraft, TestDesignPublishPackage
from app.services import audit_service
from app.services import test_design_version_service as test_design_version_svc


def _jira_description_lines(draft: TestCaseDraft) -> list[str]:
    lines: list[str] = [
        f"Title:\n{draft.title}",
        f"Category:\n{draft.case_type}",
        f"Objective:\n{draft.objective or '(not specified)'}",
        "Preconditions:",
    ]
    if draft.preconditions:
        lines.extend(f"- {p}" for p in draft.preconditions)
    else:
        lines.append("- (none listed)")
    lines.append("")
    lines.append("Test Steps:")
    if draft.steps:
        for i, s in enumerate(draft.steps, start=1):
            lines.append(f"{i}. {s}")
    else:
        lines.append("1. (not specified)")
    lines.append("")
    lines.append("Expected Results:")
    if draft.expected_results:
        for i, s in enumerate(draft.expected_results, start=1):
            lines.append(f"{i}. {s}")
    else:
        lines.append("1. (not specified)")
    lines.append("")
    lines.append("Assumptions:")
    if draft.assumptions:
        lines.extend(f"- {a}" for a in draft.assumptions)
    else:
        lines.append("- (none listed)")
    lines.append("")
    lines.append("Missing Information:")
    if draft.missing_information:
        lines.extend(f"- {m}" for m in draft.missing_information)
    else:
        lines.append("- (none listed)")
    lines.append("")
    lines.append("Generated by:\nQSwarm Sprint 1 draft test design")
    return lines


class JiraTestDesignPublisher(TestDesignPublisher):
    """Creates linked Jira Tasks from a ``TestDesignPublishPackage``."""

    def __init__(self, jira: JiraClient, settings: Settings):
        self._jira = jira
        self._settings = settings

    def publish(
        self,
        package: TestDesignPublishPackage,
        *,
        db: Session,
        workflow_run_id: uuid.UUID,
        reviewer_account_id: str | None = None,
    ) -> PublishResult:
        actor = "jira_test_design_publisher"
        audit_service.write_audit(
            db,
            event_type=AuditEventType.TEST_DESIGN_PUBLISH_STARTED.value,
            actor_type=ActorType.SYSTEM.value,
            actor_id=actor,
            workflow_run_id=workflow_run_id,
            step_name="publish_test_design",
            entity_type="workflow_run",
            entity_id=str(workflow_run_id),
            payload={
                "target": "jira",
                "parent_issue_key": package.parent_issue_key,
                "case_count": len(package.cases),
            },
        )
        db.flush()

        if not package.cases:
            audit_service.write_audit(
                db,
                event_type=AuditEventType.TEST_DESIGN_PUBLISH_COMPLETED.value,
                actor_type=ActorType.SYSTEM.value,
                actor_id=actor,
                workflow_run_id=workflow_run_id,
                step_name="publish_test_design",
                entity_type="workflow_run",
                entity_id=str(workflow_run_id),
                payload={"target": "jira", "skipped": True, "reason": "no_cases"},
            )
            db.flush()
            return PublishResult(success=True, hard_failure=False, warnings=["no_draft_cases_to_publish"])

        try:
            project_key = project_key_from_issue_key(package.parent_issue_key)
        except JiraClientError as e:
            audit_service.write_audit(
                db,
                event_type=AuditEventType.TEST_DESIGN_PUBLISH_FAILED.value,
                actor_type=ActorType.SYSTEM.value,
                actor_id=actor,
                workflow_run_id=workflow_run_id,
                step_name="publish_test_design",
                entity_type="workflow_run",
                entity_id=str(workflow_run_id),
                payload={"error": str(e)},
            )
            db.flush()
            return PublishResult(success=False, hard_failure=True, errors=[str(e)])

        reviewer = (reviewer_account_id or self._settings.jira_default_test_reviewer_account_id or "").strip() or None

        created_keys: list[str] = []
        warnings: list[str] = []
        sync_ver = test_design_version_svc.get_current_version_number(db, workflow_run_id) or 1

        for case_index, draft in enumerate(package.cases):
            summary = f"Test Case: {draft.title}"[:254]
            desc_adf = plain_lines_to_adf(_jira_description_lines(draft))
            try:
                resp = self._jira.create_issue(
                    project_key=project_key,
                    summary=summary,
                    description_adf=desc_adf,
                    issue_type_name="Task",
                    labels=["qswarm-draft-test-case"],
                )
                child_key = str(resp.get("key") or "").strip().upper()
                if not child_key:
                    raise JiraClientError("Jira create_issue returned empty key", status_code=500)
            except JiraClientError as e:
                err = str(e)[:2000]
                row = JiraGeneratedTestCase(
                    workflow_run_id=workflow_run_id,
                    parent_jira_issue_key=package.parent_issue_key,
                    generated_jira_issue_key=None,
                    artifact_id=package.source_artifact_id,
                    title=draft.title[:500],
                    case_type=draft.case_type,
                    reviewer_account_id=reviewer,
                    external_system="jira",
                    publish_status="failed",
                    link_status="skipped",
                    assignment_status="not_attempted",
                    error_detail=err,
                    case_index=case_index,
                    internal_sync_version=sync_ver,
                    jira_sync_status="failed",
                    last_sync_error=err,
                )
                db.add(row)
                db.flush()
                audit_service.write_audit(
                    db,
                    event_type=AuditEventType.TEST_DESIGN_PUBLISH_FAILED.value,
                    actor_type=ActorType.SYSTEM.value,
                    actor_id=actor,
                    workflow_run_id=workflow_run_id,
                    step_name="publish_test_design",
                    entity_type="jira_generated_test_case",
                    entity_id=str(row.id),
                    payload={"error": err[:500], "title": draft.title[:200]},
                )
                db.flush()
                if not created_keys:
                    return PublishResult(
                        success=False,
                        hard_failure=True,
                        errors=[err],
                        warnings=warnings,
                    )
                warnings.append(f"create_failed:{draft.title[:80]}:{err[:200]}")
                continue

            row = JiraGeneratedTestCase(
                workflow_run_id=workflow_run_id,
                parent_jira_issue_key=package.parent_issue_key,
                generated_jira_issue_key=child_key,
                artifact_id=package.source_artifact_id,
                title=draft.title[:500],
                case_type=draft.case_type,
                reviewer_account_id=reviewer,
                external_system="jira",
                publish_status="published",
                link_status="skipped",
                assignment_status="not_attempted",
                error_detail=None,
                case_index=case_index,
                internal_sync_version=sync_ver,
                jira_sync_status="published",
                last_sync_error=None,
            )
            db.add(row)
            db.flush()

            audit_service.write_audit(
                db,
                event_type=AuditEventType.JIRA_TEST_CASE_CREATED.value,
                actor_type=ActorType.SYSTEM.value,
                actor_id=actor,
                workflow_run_id=workflow_run_id,
                step_name="publish_test_design",
                entity_type="jira_generated_test_case",
                entity_id=str(row.id),
                payload={"generated_jira_issue_key": child_key, "parent": package.parent_issue_key},
            )
            db.flush()

            try:
                self._jira.link_issues(
                    inward_issue_key=child_key,
                    outward_issue_key=package.parent_issue_key,
                    link_type_name="Relates",
                )
                row.link_status = "linked"
                audit_service.write_audit(
                    db,
                    event_type=AuditEventType.JIRA_TEST_CASE_LINKED.value,
                    actor_type=ActorType.SYSTEM.value,
                    actor_id=actor,
                    workflow_run_id=workflow_run_id,
                    step_name="publish_test_design",
                    entity_type="jira_generated_test_case",
                    entity_id=str(row.id),
                    payload={"child": child_key, "parent": package.parent_issue_key},
                )
                db.flush()
            except JiraClientError as e:
                row.link_status = "failed"
                msg = str(e)[:800]
                warnings.append(f"link_failed:{child_key}:{msg}")
                audit_service.write_audit(
                    db,
                    event_type=AuditEventType.JIRA_TEST_CASE_LINK_FAILED.value,
                    actor_type=ActorType.SYSTEM.value,
                    actor_id=actor,
                    workflow_run_id=workflow_run_id,
                    step_name="publish_test_design",
                    entity_type="jira_generated_test_case",
                    entity_id=str(row.id),
                    payload={"child": child_key, "error": msg[:500]},
                )
                db.flush()

            if reviewer:
                try:
                    self._jira.assign_issue(child_key, reviewer)
                    row.assignment_status = "assigned"
                except JiraClientError as e:
                    row.assignment_status = "failed"
                    msg = str(e)[:800]
                    warnings.append(f"assign_failed:{child_key}:{msg}")
                    audit_service.write_audit(
                        db,
                        event_type=AuditEventType.JIRA_TEST_CASE_ASSIGNMENT_FAILED.value,
                        actor_type=ActorType.SYSTEM.value,
                        actor_id=actor,
                        workflow_run_id=workflow_run_id,
                        step_name="publish_test_design",
                        entity_type="jira_generated_test_case",
                        entity_id=str(row.id),
                        payload={"child": child_key, "error": msg[:500]},
                    )
                    db.flush()
            else:
                row.assignment_status = "skipped"

            db.flush()
            created_keys.append(child_key)

        if created_keys:
            summary_lines = [
                "QSwarm Sprint 1 published draft Jira Task(s) for human review in QSwarm.",
                f"Tasks created ({len(created_keys)}): {', '.join(created_keys)}",
            ]
            try:
                self._jira.add_comment(
                    package.parent_issue_key,
                    plain_lines_to_adf(summary_lines),
                )
                audit_service.write_audit(
                    db,
                    event_type=AuditEventType.JIRA_PARENT_COMMENT_ADDED.value,
                    actor_type=ActorType.SYSTEM.value,
                    actor_id=actor,
                    workflow_run_id=workflow_run_id,
                    step_name="publish_test_design",
                    entity_type="jira_issue",
                    entity_id=package.parent_issue_key,
                    payload={"created_keys": created_keys},
                )
                db.flush()
            except JiraClientError as e:
                msg = str(e)[:800]
                warnings.append(f"parent_comment_failed:{msg}")
                audit_service.write_audit(
                    db,
                    event_type=AuditEventType.JIRA_PARENT_COMMENT_FAILED.value,
                    actor_type=ActorType.SYSTEM.value,
                    actor_id=actor,
                    workflow_run_id=workflow_run_id,
                    step_name="publish_test_design",
                    entity_type="jira_issue",
                    entity_id=package.parent_issue_key,
                    payload={"error": msg[:500]},
                )
                db.flush()

        audit_service.write_audit(
            db,
            event_type=AuditEventType.TEST_DESIGN_PUBLISH_COMPLETED.value,
            actor_type=ActorType.SYSTEM.value,
            actor_id=actor,
            workflow_run_id=workflow_run_id,
            step_name="publish_test_design",
            entity_type="workflow_run",
            entity_id=str(workflow_run_id),
            payload={"created_keys": created_keys, "warning_count": len(warnings)},
        )
        db.flush()

        return PublishResult(
            success=True,
            hard_failure=False,
            created_issue_keys=created_keys,
            warnings=warnings,
        )
