"""Plain-text lines for the single Sprint 1 Jira draft test design review Task description."""

from __future__ import annotations

from typing import Any


def build_review_issue_description_lines(
    *,
    parent_issue_key: str,
    design: dict[str, Any],
) -> list[str]:
    pk = parent_issue_key.strip().upper()
    lines: list[str] = [
        "Title:",
        f"Draft Test Design for {pk}",
        "",
        "Generated Scenarios:",
    ]
    scenarios = design.get("scenario_set") or []
    if not isinstance(scenarios, list):
        scenarios = []
    n = 0
    for raw in scenarios:
        if not isinstance(raw, dict):
            continue
        title = str(raw.get("title") or "").strip()
        if not title:
            continue
        n += 1
        ctype = str(raw.get("type") or "generic").strip().lower()
        lines.append(f"{n}. [{ctype}] {title}")
    if n == 0:
        lines.append("(none)")

    cov: set[str] = set()
    for raw in scenarios:
        if isinstance(raw, dict) and raw.get("type"):
            cov.add(str(raw["type"]).strip().lower())
    lines.extend(["", "Coverage:"])
    if cov:
        for c in sorted(cov):
            lines.append(f"- {c}")
    else:
        lines.append("- (not classified)")

    lines.extend(["", "Assumptions:"])
    assumptions = design.get("assumptions") or []
    if isinstance(assumptions, list) and assumptions:
        for a in assumptions[:12]:
            lines.append(f"- {str(a)[:500]}")
    else:
        lines.append("- (none listed)")

    lines.extend(["", "Missing Information:"])
    data_needs = design.get("data_needs") or []
    if isinstance(data_needs, list) and data_needs:
        for d in data_needs[:8]:
            lines.append(f"- {str(d)[:500]}")
    else:
        lines.append("- (none listed)")

    lines.extend(
        [
            "",
            "Review Instructions:",
            "Comment with `@QSwarm` followed by your requested changes.",
            "Examples:",
            "- @QSwarm add more negative scenarios",
            "- @QSwarm make this more stepwise",
            "- @QSwarm simplify the edge cases",
            "",
            "Generated by:",
            "QSwarm Sprint 1",
        ]
    )
    return lines
